# /etc/suritop-web/collector.conf
# suritop-web collector configuration
# Variables are substituted during emerge by pkg_postinst()

[Network]
our_ip = @@SERVER_IP@@

[Database]
host = localhost
name = server_stats
user_r = stats_reader
pass_r = CHANGE_ME
user_w = stats_writer
pass_w = CHANGE_ME

[Interfaces]
monitor = @@NET_INTERFACE@@
