<?php
/**
 * suritop-web root config — generated by: emerge --config net-analyzer/suritop-web
 * Do NOT edit manually — re-run emerge --config to regenerate.
 */
define('STATS_DB_HOST', 'localhost');
define('STATS_DB_NAME', 'server_stats');
define('STATS_DB_USER', 'stats_reader');
define('STATS_DB_PASS', 'suritop_read_2026');
define('OUR_IP', '@@SERVER_IP@@');
define('CACHE_FILE', '/tmp/attack_replay_cache.json');
define('CACHE_TTL', 300);
define('RT_POLL_INTERVAL', 5000);
define('RT_MIN_DELAY', 200);
define('RT_FETCH_LIMIT', 50);
define('STATS_REFRESH_INTERVAL', 30000);
define('CHARTS_REFRESH_INTERVAL', 120000);
define('DEFAULT_THEME', 'dark');
define('ATTACKMAP_BASE_URL', '/attackmap/');
define('WAF_BASE_URL', '/admin_stats.php');

function getServerLocation() {
    $ip = defined('OUR_IP') ? OUR_IP : '';
    if (!$ip || $ip === '127.0.0.1') return [30.0, 10.0];
    $cache = '/tmp/suritop_server_geo.json';
    if (file_exists($cache) && (time() - filemtime($cache)) < 86400) {
        $data = json_decode(file_get_contents($cache), true);
        if ($data && isset($data['lat']) && isset($data['lon'])) return [$data['lat'], $data['lon']];
    }
    $ctx = stream_context_create(['http' => ['timeout' => 3]]);
    $json = @file_get_contents("http://ip-api.com/json/{$ip}?fields=lat,lon", false, $ctx);
    if ($json) {
        $d = json_decode($json, true);
        if ($d && isset($d['lat']) && isset($d['lon'])) {
            file_put_contents($cache, json_encode($d));
            return [$d['lat'], $d['lon']];
        }
    }
    return [30.0, 10.0];
}
