# /etc/conf.d/suritop-web
# suritop-web init script configuration (shell format for OpenRC)
# Application config: /etc/suritop-web/suritop.conf

SURITOP_AUTO_IPTABLES="no"
SURITOP_SERVER_IP="@@SERVER_IP@@"
SURITOP_NET_INTERFACE="@@NET_INTERFACE@@"
SURITOP_SSH_PORT="@@SSH_PORT@@"
SURITOP_WHITELIST_IP="@@SERVER_IP@@"
SURITOP_NAT_ENABLE="no"
SURITOP_DOCKER_ENABLE="no"
SURITOP_DOCKER_BRIDGE="172.17.0.0/16"
