<?php
/**
 * suritop-web attackmap config — generated by: emerge --config net-analyzer/suritop-web
 */
define('STATS_DB_HOST', '');
define('STATS_DB_NAME', '');
define('STATS_DB_USER', '');
define('STATS_DB_PASS', '');
define('OUR_IP', '');
define('SERVER_LAT', 0);
define('SERVER_LON', 0);
define('CACHE_FILE', '/tmp/attack_replay_cache.json');
define('CACHE_TTL', 300);
define('RT_POLL_INTERVAL', 5000);
define('RT_MIN_DELAY', 200);
define('RT_FETCH_LIMIT', 50);
define('STATS_REFRESH_INTERVAL', 30000);
define('CHARTS_REFRESH_INTERVAL', 120000);
define('DEFAULT_THEME', 'dark');
define('ATTACKMAP_BASE_URL', '/attackmap/');
define('WAF_BASE_URL', '/admin_stats.php');
